export const SKILL_DATA = [
  {
    skillId: "SKILL_HORN_AQUA_ANEMONE",
    skillName: "Anemone",
    skillDescription:
      "Summon a sparkly anemone which spawns healing orbs around the area!",
    lvlUpText: {
      lvlUp1: "Heal +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Heal +25%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Heal +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Heal +25%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_ANT",
    skillName: "Ant",
    skillDescription:
      "Unleash a toxic explosion, damaging and burning all nearby monsters!",
    lvlUpText: {
      lvlUp1: "Increase Area",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Burn Duration +50%",
      lvlUp5: "Increase Area",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Burn Duration +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_ANTENNA",
    skillName: "Antenna",
    skillDescription:
      "Summon fireflies which explode into beams of sedating moonlight!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BEAST_AXIEKISS",
    skillName: "Axie Kiss",
    skillDescription:
      "Give your enemies a deadly kiss, marking them and healing your wounds!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_BAMBOOSHOOT",
    skillName: "Bamboo Shoot",
    skillDescription: "Impale nearby monsters with a surprise spear attack!",
    lvlUpText: {
      lvlUp1: "Bamboo +1",
      lvlUp2: "Bamboo +1",
      lvlUp3: "Bamboo +1",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Bamboo +1",
      lvlUp6: "Bamboo +1",
      lvlUp7: "Bamboo +1",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_BLUEMOON",
    skillName: "Blue Moon",
    skillDescription:
      "Summon rotating crescent orbs which explode and put monsters to sleep!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Crescent Orb +1, Increase Sleep Chance",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Crescent Orb +1, Increase Sleep Chance",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_BONESAIL",
    skillName: "Bone Sail",
    skillDescription:
      "Plant a trap to lure greedy monsters. Explodes on contact!",
    lvlUpText: {
      lvlUp1: "Increase Explosion Radius",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Explosion Radius",
      lvlUp4: "Chest +1",
      lvlUp5: "Increase Explosion Radius",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Explosion Radius",
      lvlUp8: "Chest +1",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_BUMPY",
    skillName: "Bumpy",
    skillDescription:
      "Gain a crystal shield that absorbs damage. When it breaks, it damages and freezes nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Freeze Duration +4sec & Freeze Chance +25%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Freeze Duration +4sec & Freeze Chance +25%",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_CARROT",
    skillName: "Carrot",
    skillDescription: "Smash a nearby area with a giant carrot hammer!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_CACTUS",
    skillName: "Cactus",
    skillDescription: "Smash a nearby area with a giant cactus club!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_CERASTES",
    skillName: "Cerastes",
    skillDescription:
      "Plant a deadly dagger trap which slice monsters on contact!",
    lvlUpText: {
      lvlUp1: "Increase Explosion Radius",
      lvlUp2: "Damage +25%",
      lvlUp3: "Increase Explosion Radius",
      lvlUp4: "Damage +25%, Cooldown -25%",
      lvlUp5: "Increase Explosion Radius",
      lvlUp6: "Damage +25%",
      lvlUp7: "Increase Explosion Radius",
      lvlUp8: "Damage +25%, Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_HORN_AQUA_CLAMSHELL",
    skillName: "Clamshell",
    skillDescription: "Summon smiley shells with a medium-range orbit!",
    lvlUpText: {
      lvlUp1: "Speed +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Speed +25%",
      lvlUp4: "Clamshell +1",
      lvlUp5: "Speed +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Speed +25%",
      lvlUp8: "Clamshell +1",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_CLOUD",
    skillName: "Cloud",
    skillDescription:
      "Summon mischievous clouds with thunderous attitude!\nStorm is coming! ",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Thunders +2",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Cloud +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Thunders +2",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Cloud +1",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_CUPID",
    skillName: "Cupid",
    skillDescription:
      "Summon a rain of homing charming cupid arrows!\nLovely! <3",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cupid Arrows +2",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Love Zone +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cupid Arrows +2",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Love Zone +1",
    },
  },
  {
    skillId: "SKILL_MOUTH_BIRD_DOUBLETALK",
    skillName: "Doubletalk",
    skillDescription:
      "Unleash a musical explosion which puts monsters to sleep!",
    lvlUpText: {
      lvlUp1: "Increase Area",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Sleep Duration +50%, Increase Sleep Chance",
      lvlUp5: "Increase Area",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Sleep Duration +50%, Increase Sleep Chance",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_DUALBLADE",
    skillName: "Dual Blade",
    skillDescription:
      "Throw lightsabers that slice through monsters and spin back to you!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Damage +25%, Cooldown -25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Damage +25%, Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_EGGSHELL",
    skillName: "Eggshell",
    skillDescription:
      "Throw exploding eggs onto the battlefield which create deadly fried eggs on impact!",
    lvlUpText: {
      lvlUp1: "Egg Bomb +1",
      lvlUp2: "Egg Bomb +1",
      lvlUp3: "Egg Bomb +1",
      lvlUp4: "Egg Bomb +1, Increase Area",
      lvlUp5: "Egg Bomb +1",
      lvlUp6: "Egg Bomb +1",
      lvlUp7: "Egg Bomb +1",
      lvlUp8: "Egg Bomb +1, Increase Area",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_FEATHERFAN",
    skillName: "Feather Fan",
    skillDescription:
      "Throw a barrage of feather fans which shred all monsters in its path!",
    lvlUpText: {
      lvlUp1: "Feather Fan +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Feather Fan +1",
      lvlUp4: "Damage +25%, Cooldown -25%",
      lvlUp5: "Feather Fan +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Feather Fan +1",
      lvlUp8: "Damage +25%, Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_FEATHERSPEAR",
    skillName: "Feather Spear",
    skillDescription: "Stab nearby monsters with mighty spear thrusts!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Spear +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Spear +2",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_FISHSNACK",
    skillName: "Fish Snack",
    skillDescription:
      "Lure your enemies with some fish snacks.\nMark any monsters who dare to eat it!",
    lvlUpText: {
      lvlUp1: "Fish Snack +1",
      lvlUp2: "Duration +25%",
      lvlUp3: "Fish Snack +1",
      lvlUp4: "Duration +25%, Marked Duration +25%, Increase Mark Chance",
      lvlUp5: "Fish Snack +1",
      lvlUp6: "Duration +25%",
      lvlUp7: "Fish Snack +1",
      lvlUp8: "Duration +25%, Marked Duration +25%, Increase Mark Chance",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_FURBALL",
    skillName: "Furball",
    skillDescription:
      "Juggle bouncing furballs while moving. Stop and throw them at monsters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -25%, Damage +25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -25%, Damage +25%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_GERBIL",
    skillName: "Gerbil",
    skillDescription:
      "Summon a fearsome gerbil to your aid. All monsters beware its presence!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Gerbil +1",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Gerbil +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Gerbil +1",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Gerbil +2",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_GILA",
    skillName: "Gila",
    skillDescription: "Leave a trail of poisonous gas. Deadly!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Gila Tails +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Gila Tails +2",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_GRASSSNAKE",
    skillName: "Grass Snake",
    skillDescription:
      "Shoot snake-like bullets from your tail to damage and poison monsters!",
    lvlUpText: {
      lvlUp1: "Grass Snake +1",
      lvlUp2: "Grass Snake +1",
      lvlUp3: "Grass Snake +1",
      lvlUp4: "Grass Snake +1, Poison Duration +25%",
      lvlUp5: "Grass Snake +1",
      lvlUp6: "Grass Snake +1",
      lvlUp7: "Grass Snake +1",
      lvlUp8: "Grass Snake +1, Poison Duration +25%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_HARE",
    skillName: "Hare",
    skillDescription:
      "Throw forward carrot daggers that can deal critical damage!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_HORN_AQUA_BABYLONIA",
    skillName: "Babylonia",
    skillDescription: "Throw forward sharp shell daggers!",
    lvlUpText: {
      lvlUp1: "Dagger +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Dagger +1",
      lvlUp4: "Cooldown -30%",
      lvlUp5: "Dagger +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Dagger +1",
      lvlUp8: "Cooldown -30%",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_HATSUNE",
    skillName: "Hatsune",
    skillDescription:
      "Leave behind a deadly spinning leek. Touch some grass or die!",
    lvlUpText: {
      lvlUp1: "Hits 2 More Enemies",
      lvlUp2: "Damage +25",
      lvlUp3: "Hits 2 More Enemies",
      lvlUp4: "Leek +1",
      lvlUp5: "Hits 2 More Enemies",
      lvlUp6: "Damage +25",
      lvlUp7: "Hits 2 More Enemies",
      lvlUp8: "Leek +1",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_HERMIT",
    skillName: "Hermit",
    skillDescription:
      "Summon a friendly hermit crab. Give him a hug to gain its protection!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_HERO",
    skillName: "Hero",
    skillDescription:
      "Gain a valiant shield that absorbs damage.\nWhen it breaks, it damages nearby monsters with heroic energy!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_HOTBUTT",
    skillName: "Hot Butt",
    skillDescription:
      "Leave a trail of spicy peppers, burning all monsters who dare to bite them!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Pepper +1",
      lvlUp3: "Burn Duration +25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Pepper +1",
      lvlUp7: "Burn Duration +25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_IMP",
    skillName: "Imp",
    skillDescription:
      "Charge a poweful energy beam that annihilates all monsters on its path!",
    lvlUpText: {
      lvlUp1: "Increase Area",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Damage +50%",
      lvlUp5: "Increase Area",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_KINGFISHER",
    skillName: "Kingfisher",
    skillDescription:
      "Gain a shield that absorbs damage. When it breaks, it damages and marks nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_REPTILE_KOTARO",
    skillName: "Kotaro",
    skillDescription:
      "Throw ninja shurikens which move in a large arc and spin back to you!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Ninja Shuriken +1",
      lvlUp3: "Damage +25%",
      lvlUp4: "Ninja Shuriken +1, Cooldown -25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Ninja Shuriken +1",
      lvlUp7: "Damage +25%",
      lvlUp8: "Ninja Shuriken +1, Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BIRD_LITTLEOWL",
    skillName: "Little Owl",
    skillDescription:
      "Summon an enchanted owl to your aid. No monster can stand its burning sight!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_MINT",
    skillName: "Mint",
    skillDescription:
      "Gain a shield that absorbs damage. It heals your wounds when it breaks!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BUG_MOSQUITO",
    skillName: "Mosquito",
    skillDescription:
      "Drain blood of nearby monsters and heal your wounds!\nThirsty!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Range +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Range +25%, Cooldown -25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Range +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Range +25%, Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BEAST_NUTCRACKER",
    skillName: "Nut Cracker",
    skillDescription:
      "Summon acorn bullets that bounce off walls. Stop moving to release deez nutz!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -25%, Damage +25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -25%, Damage +25%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_NUTCRACKER",
    skillName: "Nut Cracker",
    skillDescription:
      "Summon walnuts that bounce off monsters. Stop moving to release deez nutz!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -25%, Damage +25%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -25%, Damage +25%",
    },
  },
  {
    skillId: "SKILL_HORN_AQUA_ORANDA",
    skillName: "Oranda",
    skillDescription: "Strike monsters with mighty swords from the sky!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Sword's Range Increased",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Sword's Range Increased",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_POCKY",
    skillName: "Pocky",
    skillDescription:
      "Attack nearby monsters with a spear attack and charming rainbow lightning!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_POTATOLEAF",
    skillName: "Potato Leaf",
    skillDescription:
      "Plant saplings which throw deadly leaf shurikens when you stop moving!",
    lvlUpText: {
      lvlUp1: "Pierce +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Pierce +1",
      lvlUp4: "Leaf +2",
      lvlUp5: "Pierce +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Pierce +1",
      lvlUp8: "Leaf +2",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_PUMPKIN",
    skillName: "Pumpkin",
    skillDescription: "Summon spooky cursed pumpkins with a long-range orbit!",
    lvlUpText: {
      lvlUp1: "Speed +25%",
      lvlUp2: "Pumpkin +1",
      lvlUp3: "Speed +25%",
      lvlUp4: "Pumpkin +1, Duration +25%",
      lvlUp5: "Speed +25%",
      lvlUp6: "Pumpkin +1",
      lvlUp7: "Speed +25%",
      lvlUp8: "Pumpkin +1, Duration +25%",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_RANCHU",
    skillName: "Ranchu",
    skillDescription:
      "Unleash a frost explosion which can freeze nearby monsters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Freeze Duration +50%, Increase Freeze Chance",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Freeze Duration +50%, Increase Freeze Chance",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_RAVEN",
    skillName: "Raven",
    skillDescription:
      "Summon an enchanted raven to your aid. No monster can stand its accursed sight!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_REPTILE_RAZORBITE",
    skillName: "Razor Bite",
    skillDescription:
      "Crunch your enemies, scare them away, and heal your wounds. Yummy!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_RICE",
    skillName: "Rice",
    skillDescription:
      "Lure your enemies with some tasty bowls of rice. Whoever eats it gets sleepy!",
    lvlUpText: {
      lvlUp1: "Rice Bowl +1",
      lvlUp2: "Duration +25%",
      lvlUp3: "Rice Bowl +1",
      lvlUp4: "Duration +25%, Sleep Duration +25%, Increase Sleep Chance",
      lvlUp5: "Rice Bowl +1",
      lvlUp6: "Duration +25%",
      lvlUp7: "Rice Bowl +1",
      lvlUp8: "Duration +25%, Sleep Duration +25%, Increase Sleep Chance",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_RONIN",
    skillName: "Ronin",
    skillDescription: "Slash nearby monsters with deadly katanas!",
    lvlUpText: {
      lvlUp1: "Increase Area",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Damage +50%",
      lvlUp5: "Increase Area",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_SCALYSPEAR",
    skillName: "Scaly Spear",
    skillDescription: "Summon a deadly row of sharp spears!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Spear +5",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Spear +5",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_SHIITAKE",
    skillName: "Shiitake",
    skillDescription:
      "Summon a lil shroom. Collect it to heal and release a poisonous cloud. The more it grows, the more it heals!",
    lvlUpText: {
      lvlUp1: "Heal +25%",
      lvlUp2: "Heal +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Heal +25%",
      lvlUp6: "Heal +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_AQUA_SHOALSTAR",
    skillName: "Shoal Star",
    skillDescription: "Keep nearby monsters at bay with starfish shurikens!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Starfish +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Starfish +1",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_SHRIMP",
    skillName: "Shrimp",
    skillDescription:
      "Leave a trail of frozen shrimps, freezing all hungry monsters!",
    lvlUpText: {
      lvlUp1: "Shrimp +1",
      lvlUp2: "Duration +25%",
      lvlUp3: "Shrimp +1",
      lvlUp4: "Duration +25%, Freeze Duration +25%, Increase Freeze Chance",
      lvlUp5: "Shrimp +1",
      lvlUp6: "Duration +25%",
      lvlUp7: "Shrimp +1",
      lvlUp8: "Duration +25%, Freeze Duration +25%, Increase Freeze Chance",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_SNAKEJAR",
    skillName: "Snake Jar",
    skillDescription:
      "Launch a jar barrage! Jars curse monsters and release poisonous snake-like bullets on impact!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Snake Jar +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Snake Jar +1",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_STRAWBERRYSHORTCAKE",
    skillName: "Strawberry Shortcake",
    skillDescription:
      "Summon a slow giant orbitting strawberry. Squash and charm monsters with this delicious treat!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Attack Speed +50% Increased Charmed Duration",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Attack Speed +50% Increased Charmed Duration",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_TADPOLE",
    skillName: "Tadpole",
    skillDescription:
      "Shoot exploding black bubbles which mark all monsters on their way!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Bubble +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Bubble +1",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_TIMBER",
    skillName: "Timber",
    skillDescription: "Swipe a mighty axe and obliterate your enemies!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_TINYDINO",
    skillName: "Tiny Dino",
    skillDescription: "Smash your enemies with a mighty stomp. Raaarr!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Stomp Size +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Stomp Size +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_THELASTONE",
    skillName: "The Last One",
    skillDescription: "Throw forward marking feathers with a deadly last shot!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_TRIFEATHER",
    skillName: "Tri Feather",
    skillDescription: "Shoot three sharp feathers from your tail!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Feathers +3",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Feathers +3",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_TRISPIKES",
    skillName: "Tri Spikes",
    skillDescription: "Shoot forward three slow piercing spikes!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Spikes +3",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Spikes +3",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_TRUMP",
    skillName: "Trump",
    skillDescription:
      "Impale nearby monsters with a spear attack!\nThen blast them with an extra stellar beam!",
    lvlUpText: {
      lvlUp1: "Red White & Blue Beam +1",
      lvlUp2: "Red White & Blue Beam +1",
      lvlUp3: "Red White & Blue Beam +1",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Red White & Blue Beam +1",
      lvlUp6: "Red White & Blue Beam +1",
      lvlUp7: "Red White & Blue Beam +1",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_TURNIP",
    skillName: "Turnip",
    skillDescription: "Launch a barrage of turnip rockets!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Turnip Rocket +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Turnip Rocket +1",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_UNKO",
    skillName: "Unko",
    skillDescription:
      "Attract monsters with a smelly poo. When stepped on... just don't!",
    lvlUpText: {
      lvlUp1: "Poop +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Poop +1",
      lvlUp4: "Bigger Poop Explosion Cooldown -25%",
      lvlUp5: "Poop +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Poop +1",
      lvlUp8: "Bigger Poop Explosion Cooldown -25%",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_WATERMELON",
    skillName: "Watermelon",
    skillDescription:
      "Throw a juicy watermelon! Breaks into damaging slices on impact!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Watermelon +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Watermelon +1",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_YAM",
    skillName: "Yam",
    skillDescription:
      "Unleash a toxic explosion, damaging and poisoning all nearby monsters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Increase Area",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Poison Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Increase Area",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Poison Duration +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_PLIERS",
    skillName: "Pliers",
    skillDescription: "Shoot munching pliers which bleed out monsters!",
    lvlUpText: {
      lvlUp1: "Plier +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Plier +1",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Plier +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Plier +1",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_SANDAL",
    skillName: "Sandal",
    skillDescription: "Smack nearby monsters with a fearsome sandal!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_SNAILSHELL",
    skillName: "Snail Shell",
    skillDescription: "Summon tough snail shells with a short-range orbit!",
    lvlUpText: {
      lvlUp1: "Speed +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Speed +25%",
      lvlUp4: "Snail Shell +1",
      lvlUp5: "Speed +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Speed +25%",
      lvlUp8: "Snail Shell +1",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_ROSEBUD",
    skillName: "Rose Bud",
    skillDescription:
      "Summon a blooming rose which emanates healing energy and charms nearby monsters!",
    lvlUpText: {
      lvlUp1: "Increase Heal Area",
      lvlUp2: "Heal +25%",
      lvlUp3: "Increase Heal Area",
      lvlUp4: "Heal +25% Duration +25%",
      lvlUp5: "Increase Heal Area",
      lvlUp6: "Heal +25%",
      lvlUp7: "Increase Heal Area",
      lvlUp8: "Heal +25% Duration +25%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_SCARAB",
    skillName: "Scarab",
    skillDescription:
      "Gain a spooky shield that absorbs damage. When it breaks, it damages and curses nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BUG_CUTEBUNNY",
    skillName: "Cute Bunny",
    skillDescription:
      "Summon cute bunnies to your aid! Their favourite food is monsters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Bunny +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Bunny +1",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_GRAVELANT",
    skillName: "Gravel Ant",
    skillDescription: "Shoot sticky strange goo that terrifies monsters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Ants +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Ants +2",
    },
  },
  {
    skillId: "SKILL_HORN_AQUA_TEALSHELL",
    skillName: "Teal Shell",
    skillDescription: "Summon frosty shells with a long-range orbit!",
    lvlUpText: {
      lvlUp1: "Speed +25%",
      lvlUp2: "Teal Shell +1",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Teal Shell +1, Duration +25%",
      lvlUp5: "Speed +25%",
      lvlUp6: "Teal Shell +1",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Teal Shell +1, Duration +25%",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_RISKYBEAST",
    skillName: "Risky Beast",
    skillDescription:
      "Create a damaging aura of beastly energy! Punish attacking monsters with burning arrows!",
    lvlUpText: {
      lvlUp1: "Attack Speed +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Attack Speed +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Attack Speed +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Attack Speed +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_WINGHORN",
    skillName: "Wing Horn",
    skillDescription: "Shoot a barrage of homing projectiles!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Arrows +2",
      lvlUp4: "Arrows +4",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Arrows +2",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_SWALLOW",
    skillName: "Swallow",
    skillDescription:
      "Summon a bountiful swallow to your aid! The coconuts it drops are both yummy and deadly!",
    lvlUpText: {
      lvlUp1: "Heal +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Heal +25%",
      lvlUp4: "Coconut +2",
      lvlUp5: "Heal +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Heal +25%",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_SCALYSPOON",
    skillName: "Scaly Spoon",
    skillDescription: "Launch a barrage of cluster bomb rocks!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Bomb Rocks +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Bomb Rocks +2",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_ARCO",
    skillName: "Arco",
    skillDescription: "Sharpen your senses, gaining shield and speed boost!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Boost Move Speed +10%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Boost Move Speed +10%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_PLANT_SILENCEWHISPER",
    skillName: "Silence Whisper",
    skillDescription: "Spew a sedative poison cloud at your enemies!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Status Duration +100% Apply Chance Increased",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Status Duration +100% Apply Chance Increased",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_THORNYCATERPILLAR",
    skillName: "Thorny Caterpillar",
    skillDescription:
      "Summon hungry caterpillars that slowly chew monsters on their path! Stop moving to release them!",
    lvlUpText: {
      lvlUp1: "Caterpillars Speed -25% Duration +25%",
      lvlUp2: "Caterpillars Speed -25% Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Caterpillars Speed -25% Duration +25%",
      lvlUp6: "Caterpillars Speed -25% Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_AQUA_CATFISH",
    skillName: "Catfish",
    skillDescription: "Swallow nearby monsters and heal your wounds!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BEAST_GODA",
    skillName: "Goda",
    skillDescription:
      "Put your enemies to sleep with an outstanding musical barrage!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Status Duration +100% Apply Chance Increased",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Status Duration +100% Apply Chance Increased",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_PIGEONPOST",
    skillName: "Pigeon Post",
    skillDescription: "Send your enemies a bunch of magical surprise letters!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "You Got Mail +2",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "You Got Mail +2",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_WALLGECKO",
    skillName: "Wall Gecko",
    skillDescription:
      "Gain a scaly shield that absorbs damage!\nPick up your tail after it breaks to heal your wounds!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_REPTILE_IGUANA",
    skillName: "Iguana",
    skillDescription: "Slap nearby monsters with your tail and pointy darts!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Dart +1",
      lvlUp4: "Darts +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Dart +1",
      lvlUp8: "Cooldown -50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_TWINTAIL",
    skillName: "Twin Tail",
    skillDescription: "Stab nearby monsters with swift spear thrusts!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Spear Hits +1",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Spear Hits +1",
    },
  },
  {
    skillId: "SKILL_TAIL_BUG_PUPAE",
    skillName: "Pupae",
    skillDescription: "Plant an utterly adorable trap.\nExplodes on contact!",
    lvlUpText: {
      lvlUp1: "Crying Baby +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Crying Baby +1",
      lvlUp4: "Bigger Diaper Mess\n Cooldown -15%",
      lvlUp5: "Crying Baby +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Crying Baby +1",
      lvlUp8: "Bigger Diaper Mess\n Cooldown -15%",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_GRANMASFAN",
    skillName: "Granmas Fan",
    skillDescription:
      "Throw a barrage of fans which damage all monsters in its path\nand create cool breeze blast!",
    lvlUpText: {
      lvlUp1: "Granma's Fan +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Granma's Fan +1",
      lvlUp4: "Damage +25%\nCooldown -25%",
      lvlUp5: "Granma's Fan +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Granma's Fan +1",
      lvlUp8: "Damage +25%\nCooldown -25%",
    },
  },
  {
    skillId: "SKILL_TAIL_BIRD_POSTFIGHT",
    skillName: "Post Fight",
    skillDescription:
      "Dash through your enemies and unleash lightning strike upon them!\nStop moving to dash!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_COTTONTAIL",
    skillName: "Cottontail",
    skillDescription:
      "Gain a lunar shield that heals you when it breaks!\nCreate magical blast based on its lumination!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Burn Duration +2sec\nBurn Chance +12.5%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Burn Duration +2sec\nBurn Chance +12.5%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_BEAST_SHIBA",
    skillName: "Shiba",
    skillDescription:
      "Summon the best shiba boi to your aid.\nNo monster can stand its charming power!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_KOI",
    skillName: "Koi",
    skillDescription:
      "Summon a magical koi to you aid.\nNo monster can stand its freezing power!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_NIMO",
    skillName: "Nimo",
    skillDescription:
      "Slap nearby monsters with your tail and little fish friends!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Clown Fish +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Clown Fish +1",
    },
  },
  {
    skillId: "SKILL_TAIL_AQUA_NAVAGA",
    skillName: "Navaga",
    skillDescription:
      "Dash through your enemies and unleash an icy blast upon them!\nStop moving to dash!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_TAIL_PLANT_CATTAIL",
    skillName: "Cattail",
    skillDescription: "Shoot charming bouncy cat paws at your enemies!\nMeow!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Cattail +1",
      lvlUp3: "Damage +25%",
      lvlUp4: "Cooldown -25%\nCattail +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Cattail +1",
      lvlUp7: "Damage +25%",
      lvlUp8: "Cooldown -25%\nCattail +1",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_GREENTHORNS",
    skillName: "Green Thorns",
    skillDescription: "Shoot forward poisonous vine daggers!",
    lvlUpText: {
      lvlUp1: "Vine Dagger +1",
      lvlUp2: "Damage +25%",
      lvlUp3: "Vine Dagger +1",
      lvlUp4: "Cooldown -30%",
      lvlUp5: "Vine Dagger +1",
      lvlUp6: "Damage +25%",
      lvlUp7: "Vine Dagger +1",
      lvlUp8: "Cooldown -30%",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_INDIANSTAR",
    skillName: "Indian Star",
    skillDescription: "Summon sturdy turtle shells with a short-range orbit!",
    lvlUpText: {
      lvlUp1: "Speed +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Speed +25%",
      lvlUp4: "Indian Star +1",
      lvlUp5: "Speed +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Speed +25%",
      lvlUp8: "Indian Star +1",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_REDEAR",
    skillName: "Red Ear",
    skillDescription:
      "Gain a turtle shield!\nWhen it breaks, it knocks back and slows down nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Slow Duration +4sec\nSlow Chance +25%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Slow Duration +4sec\nSlow Chance +25%",
    },
  },
  {
    skillId: "SKILL_BACK_REPTILE_CROC",
    skillName: "Croc",
    skillDescription:
      "Summon a warrior crocodile to your aid!\nNo monster can stand its sharp spikes!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Spikes +50%",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Spikes +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_GARISHWORM",
    skillName: "Garish Worm",
    skillDescription:
      "Summon poisonous barbs that slowly pierce monsters!\nStop moving to release them!",
    lvlUpText: {
      lvlUp1: "Worms Speed -25%\nDuration +25%",
      lvlUp2: "Worms Speed -25%\nDuration +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Worms Speed -25%\nDuration +25%",
      lvlUp6: "Worms Speed -25%\nDuration +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_BUZZBUZZ",
    skillName: "Buzz Buzz",
    skillDescription:
      "Create a damaging aura of insect noise!\nPunish attacking monsters with an alluring sonic blast!",
    lvlUpText: {
      lvlUp1: "Attack Speed +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Attack Speed +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Attack Speed +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Attack Speed +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BUG_SPIKYWING",
    skillName: "Spiky Wing",
    skillDescription:
      "Dash through your enemies and deal critical blows!\nStop moving to dash!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Crit Chance +35%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Crit Chance +35%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_BIRD_BALLOON",
    skillName: "Balloon",
    skillDescription:
      "Shoot floating balloons which explode into a star barrage!",
    lvlUpText: {
      lvlUp1: "Balloon +1",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Balloon +2",
      lvlUp5: "Balloon +1",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Balloon +2",
    },
  },
  {
    skillId: "SKILL_BACK_BEAST_JAGUAR",
    skillName: "Jaguar",
    skillDescription:
      "Summon a hunter jaguar to you aid.\nNo monster can stand its predatory instinct!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_GOLDFISH",
    skillName: "Goldfish",
    skillDescription:
      "Summon a lucky goldfish to you aid.\nNo monster can stand its sleepy gaze!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Duration +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Duration +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Duration +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Duration +50%",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_SPONGE",
    skillName: "Sponge",
    skillDescription:
      "Gain a sponge shield!\nWhen it breaks, it knocks back and slows down nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Shield +25%",
      lvlUp4: "Slowed Duration +4sec\nSlowed Chance +25%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Shield +25%",
      lvlUp8: "Slowed Duration +4sec\nSlowed Chance +25%",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_ANEMONE",
    skillName: "Anemone",
    skillDescription:
      "Gain a bubble shield that boosts your speed!\nIt heals your wounds when it breaks!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Boost Move Speed +20%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Boost Move Speed +20%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_BACK_AQUA_PERCH",
    skillName: "Perch",
    skillDescription: "Pierce monsters with a row of sharp spikes!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_BIDENS",
    skillName: "Bidens",
    skillDescription:
      "Gain a flower shield that absorbs damage!\nIt regenerates your health while it's active!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Heal Duration +5sec",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Heal Duration +5sec",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_BACK_PLANT_WATERINGCAN",
    skillName: "Watering Can",
    skillDescription:
      "Summon a magical watering can which spawns healing orbs around the area!",
    lvlUpText: {
      lvlUp1: "Duration +25%",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Duration +25%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Duration +25%",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Duration +25%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_HORN_REPTILE_INCISOR",
    skillName: "Incisor",
    skillDescription:
      "Create a damaging aura of razor-sharp crystal scales!\nPunish attacking monsters with a bleed scale jab!",
    lvlUpText: {
      lvlUp1: "Attack Speed +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Attack Speed +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Attack Speed +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Attack Speed +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_LAGGING",
    skillName: "Lagging",
    skillDescription:
      "Ram your enemies with the help of slow-yet-hardy beetles!",
    lvlUpText: {
      lvlUp1: "Insects Speed -25%\nDuration +25%",
      lvlUp2: "Insects Speed -25%\nDuration +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Insects Speed -25%\nDuration +25%",
      lvlUp6: "Insects Speed -25%\nDuration +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_CATERPILLARS",
    skillName: "Caterpillars",
    skillDescription:
      "Unleash a surprise attack of stealthy grubs at your enemies!",
    lvlUpText: {
      lvlUp1: "Caterpillars Speed -25%\nDuration +25%",
      lvlUp2: "Caterpillars Speed -25%\nDuration +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Caterpillars Speed -25%\nDuration +25%",
      lvlUp6: "Caterpillars Speed -25%\nDuration +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_PARASITE",
    skillName: "Parasite",
    skillDescription: "Shoot sticky alien eye that attracts nearby monsters! ",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Eyes +2",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Eyes +4",
      lvlUp5: "Damage +25%",
      lvlUp6: "Eyes +2",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Eyes +4",
    },
  },
  {
    skillId: "SKILL_HORN_BUG_LEAFBUG",
    skillName: "Leaf Bug",
    skillDescription:
      "Hide in a shrub, gaining shield and speed!\nWhen the shield breaks, heal your wounds and charm nearby monsters!",
    lvlUpText: {
      lvlUp1: "Shield +25%",
      lvlUp2: "Cooldown -15%",
      lvlUp3: "Boost Move Speed +20%",
      lvlUp4: "Heal +50%",
      lvlUp5: "Shield +25%",
      lvlUp6: "Cooldown -15%",
      lvlUp7: "Boost Move Speed +20%",
      lvlUp8: "Heal +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_CUCKOO",
    skillName: "Cuckoo",
    skillDescription:
      "Slow down and charm your enemies with a surprising sonic blast!\nCockadoodledoo!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Status Duration +100%\nApply Chance Increased",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Status Duration +100%\nApply Chance Increased",
    },
  },
  {
    skillId: "SKILL_HORN_BIRD_KESTREL",
    skillName: "Kestrel",
    skillDescription:
      "Gain help of a brave kestrel\nwhich attacks monsters with deadly aerial slashes!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Status Duration +100%\nApply Chance Increased",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Status Duration +100%\nApply Chance Increased",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_LITTLEBRANCH",
    skillName: "Little Branch",
    skillDescription: "Crush your enemies with a powerful uppercut!\nKO!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_HORN_BEAST_MERRY",
    skillName: "Merry",
    skillDescription:
      "Dash through your enemies and gain a heroic shield!\nStop moving to dash!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Shield +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Shield +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Shield +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Shield +50%",
    },
  },
  {
    skillId: "SKILL_HORN_PLANT_BEECH",
    skillName: "Beech",
    skillDescription:
      "Dash through your enemies and summon a wooden dummy!\nStop moving to dash!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Trunk Duration +2sec",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Trunk Duration +2sec",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_REPTILE_TINYTURTLE",
    skillName: "Tiny Turtle",
    skillDescription:
      "Summon lil spinning turtles to your aid.\nThey slow down monsters on hit!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Turtle +1",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Turtle +2",
      lvlUp5: "Damage +25%",
      lvlUp6: "Turtle +1",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Turtle +2",
    },
  },
  {
    skillId: "SKILL_MOUTH_REPTILE_TOOTHLESSBITE",
    skillName: "Toothless Bite",
    skillDescription:
      "Slash and bleed out nearby monsters with a pair of deadly daggers!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Stab Distance +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Dagger Stab +1",
      lvlUp5: "Damage +25%",
      lvlUp6: "Stab Distance +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Dagger Stab +1",
    },
  },
  {
    skillId: "SKILL_MOUTH_BUG_PINCER",
    skillName: "Pincer",
    skillDescription:
      "Slash and bleed out nearby monsters with a pair of deadly pincers!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BUG_SQUARETEETH",
    skillName: "Square Teeth",
    skillDescription: "Unleash on your enemies a combo of fire punches!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Boxing Gloves +4",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Boxing Gloves +4",
    },
  },
  {
    skillId: "SKILL_MOUTH_BIRD_PEACEMAKER",
    skillName: "Peace Maker",
    skillDescription: "Greet your enemies with totally peaceful punch combo!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Cooking Gloves +4",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Cooking Gloves +4",
    },
  },
  {
    skillId: "SKILL_MOUTH_BIRD_HUNGRYBIRD",
    skillName: "Hungry Bird",
    skillDescription: "Peck all nearby monsters and heal your wounds!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_BEAST_CONFIDENT",
    skillName: "Confident",
    skillDescription: "Mark and scare monsters with a frenzy battle shout!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -15%",
      lvlUp4: "Status Duration +100%\nApply Chance Increased",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -15%",
      lvlUp8: "Status Duration +100%\nApply Chance Increased",
    },
  },
  {
    skillId: "SKILL_MOUTH_AQUA_LAM",
    skillName: "Lam",
    skillDescription:
      "Charge a mystic ice beam that shatters all monsters on its path!",
    lvlUpText: {
      lvlUp1: "Increase Area",
      lvlUp2: "Cooldown -25%",
      lvlUp3: "Increase Area",
      lvlUp4: "Damage +50%",
      lvlUp5: "Increase Area",
      lvlUp6: "Cooldown -25%",
      lvlUp7: "Increase Area",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_AQUA_RISKYFISH",
    skillName: "Risky Fish",
    skillDescription:
      "Create a damaging aura of aquatic grandeur!\nPunish attacking monsters with a marking fishhook!",
    lvlUpText: {
      lvlUp1: "Attack Speed +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Attack Speed +25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Attack Speed +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Attack Speed +25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_AQUA_PIRANHA",
    skillName: "Piranha",
    skillDescription:
      "Bite and bleed out nearby monsters with razor-sharp teeth!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_PLANT_SERIOUS",
    skillName: "Serious",
    skillDescription:
      "No monster can stand an iron fist punch!\nNo jokes here!",
    lvlUpText: {
      lvlUp1: "Cooldown -25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Iron Gloves +4",
      lvlUp5: "Cooldown -25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Iron Gloves +4",
    },
  },
  {
    skillId: "SKILL_MOUTH_PLANT_ZIGZAG",
    skillName: "ZigZag",
    skillDescription: "Munch on nearby monsters and heal your wounds!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Damage +25%",
      lvlUp3: "Cooldown -25%",
      lvlUp4: "Damage +50%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Damage +25%",
      lvlUp7: "Cooldown -25%",
      lvlUp8: "Damage +50%",
    },
  },
  {
    skillId: "SKILL_MOUTH_PLANT_HERBIVORE",
    skillName: "Herbivore",
    skillDescription:
      "Throw some healthy veggies at your enemies!\nCatch them and stack up those healthy calories!",
    lvlUpText: {
      lvlUp1: "Damage +25%",
      lvlUp2: "Heal +25%",
      lvlUp3: "Damage +25%",
      lvlUp4: "Heal +25%\nCooldown -15%",
      lvlUp5: "Damage +25%",
      lvlUp6: "Heal +25%",
      lvlUp7: "Damage +25%",
      lvlUp8: "Heal +25%\nCooldown -15%",
    },
  },
]
